name: Build and deploy ASP.Net Core app to Azure Web App - EMRSWEBAPP

on:
  push:
    branches:
      - master
    paths:
      - 'emrsCandidateService/**'  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Candidate API
        run: dotnet build ./emrsCandidateService/emrsCandidateService.csproj --configuration Release

      - name: Publish Candidate API
        run: dotnet publish ./emrsCandidateService/emrsCandidateService.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_58B926D660134B3FA73EE5BE3187C297 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F85930B91D64B669D5719810AE8A61D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_393181906EAA4EB3962294035B3DDE9A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EMRSWEBAPP'
          slot-name: 'Production'
          package: .
